# Generated by Django 5.2.7 on 2025-10-04 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название встречи', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание встречи')),
                ('latitude', models.FloatField(help_text='Широта места проведения встречи')),
                ('longitude', models.FloatField(help_text='Долгота места проведения встречи')),
                ('date_time', models.DateTimeField(help_text='Дата и время начала встречи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(help_text='Пользователь, создавший встречу', on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text='Участники встречи', related_name='participating_meetings', to=settings.AUTH_USER_MODEL)),
                ('sport_category', models.ForeignKey(blank=True, help_text='Категория спорта для этой встречи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='sf_meetings.sportcategory')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['date_time'],
            },
        ),
    ]
