# Generated by Django 5.2.7 on 2025-10-16 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок новости', max_length=255)),
                ('content', models.TextField(help_text='Содержание новости')),
                ('image', models.ImageField(blank=True, help_text='Изображение для новости', null=True, upload_to='news_photos/')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Количество просмотров новости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Опубликована ли новость')),
                ('author', models.ForeignKey(help_text='Автор новости', on_delete=django.db.models.deletion.CASCADE, related_name='authored_news', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(help_text='Связанная встреча (если применимо)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='sf_meetings.meeting')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
