# Generated by Django 5.2.7 on 2025-10-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
