# Generated by Django 5.2.7 on 2025-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf_meetings', '0002_meeting_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
