# Generated by Django 5.2.7 on 2025-10-04 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sf_meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Основное фото профиля', null=True, upload_to='profile_photos/')),
                ('second_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('find_area', models.FloatField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Telegram user ID (получается из виджета)', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_sport_profiles', to='sf_meetings.sportcategory')),
                ('meetings', models.ManyToManyField(blank=True, related_name='profiles', to='sf_meetings.meeting')),
                ('sport_categories', models.ManyToManyField(blank=True, related_name='interested_profiles', to='sf_meetings.sportcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_photos/gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_main', models.BooleanField(default=False, help_text='Главное фото?')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sf_auth.profile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
